run:
  timeout: 5m
  tests: false
linters:
   enable-all: true
   disable:
     - cyclop
     - depguard
     - exhaustivestruct
     - exhaustruct
     - funlen
     - forbidigo
     - forcetypeassert
     - gci
     - gochecknoglobals
     - gochecknoinits
     - godox
     - godot
     - goerr113
     - err113
     - gofumpt
     - gomnd
     - mnd
     - lll
     - musttag
     - nlreturn
     - nolintlint
     - nonamedreturns
     - tagliatelle
     - varnamelen
     - wrapcheck
linters-settings:
  estif:
    min-complexity: 4
  maligned:
    suggest-new: true
