run:
  timeout: 5m
  tests: false
issues:
  exclude-rules:
    - path: 'tls/cert.go'
      linters:
        - funlen
    - path: 'tls-tool.go'
      linters:
        - funlen
    - path: 'tls/cert.go'
      linters:
        - errcheck
    - path: 'tls/ca.go'
      linters:
        - errcheck
        - gocritic
    - path: 'tls/generate.go'
      linters:
        - govet
        - perfsprint
        - staticcheck
linters:
   enable-all: true
   disable:
     - cyclop
     - depguard
     - exhaustivestruct
     - exhaustruct
     - forbidigo
     - forcetypeassert
     - gci
     - gochecknoglobals
     - gochecknoinits
     - godox
     - godot
     - goerr113
     - err113
     - gofumpt
     - gomnd
     - mnd
     - lll
     - musttag
     - nlreturn
     - nolintlint
     - nonamedreturns
     - tagliatelle
     - varnamelen
     - wrapcheck
linters-settings:
  estif:
    min-complexity: 4
  maligned:
    suggest-new: true
  funlen:
    ignore-comments: true
