name: Go
on:
  push:
    branches: [ main ]
    tags:
      - v*
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: Test
        run: go test -v ./...

      - name: Build
        run: go build -v .
